import { auth, db } from "./auth.js";
import { collection, getDocs, addDoc, updateDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const dateText=v=>v?.toDate?v.toDate().toLocaleDateString("es-VE"):v||"—";
const user=()=>auth.currentUser;
const statuses=["PLANIFICACION","EN_PROGRESO","PAUSADO","COMPLETADO","CANCELADO"];
const statusLabel=s=>({PLANIFICACION:"Planificación",EN_PROGRESO:"En progreso",PAUSADO:"Pausado",COMPLETADO:"Completado",CANCELADO:"Cancelado"}[s]||s||"—");

async function read(name){const s=await getDocs(collection(db,name));return s.docs.map(d=>({id:d.id,...d.data()}));}

function formHTML(clients,quotes,project={}){
 const editing=Boolean(project.id);
 const approved=quotes.filter(q=>q.estado==="APROBADA");
 return `<div class="client-form-head"><div><span class="eyebrow">${editing?"EDITAR PROYECTO":"NUEVO PROYECTO"}</span><h2>${editing?esc(project.nombre):"Crear proyecto"}</h2></div><button type="button" class="btn-secondary" data-action="close-form">Cerrar</button></div><form id="projectForm" data-id="${esc(project.id||"")}"><div class="form-grid"><label>Nombre del proyecto *<input name="nombre" required maxlength="150" value="${esc(project.nombre)}" placeholder="Nombre del proyecto"></label><label>Cliente<select name="clienteId"><option value="">Sin cliente asociado</option>${clients.map(c=>`<option value="${esc(c.id)}" ${project.clienteId===c.id?"selected":""}>${esc(c.nombre)}${c.rif?` · ${esc(c.rif)}`:""}</option>`).join("")}</select></label><label>Presupuesto asociado<select name="presupuestoId"><option value="">Sin presupuesto asociado</option>${approved.map(q=>`<option value="${esc(q.id)}" ${project.presupuestoId===q.id?"selected":""}>${esc(q.numero||"Sin número")} · ${esc(q.clienteNombre||"")} · $${Number(q.totalUSD||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}</option>`).join("")}</select><small class="field-help">Solo se muestran presupuestos aprobados.</small></label><label>Estado<select name="estado">${statuses.map(s=>`<option value="${s}" ${(project.estado||"PLANIFICACION")===s?"selected":""}>${statusLabel(s)}</option>`).join("")}</select></label><label>Responsable<input name="responsable" maxlength="120" value="${esc(project.responsable)}" placeholder="Responsable interno"></label><label>Fecha de inicio<input name="fechaInicio" type="date" value="${esc(project.fechaInicio)}"></label><label>Fecha estimada de cierre<input name="fechaFin" type="date" value="${esc(project.fechaFin)}"></label><label class="form-full">Descripción<textarea name="descripcion" rows="3" maxlength="800" placeholder="Alcance y objetivo del proyecto">${esc(project.descripcion)}</textarea></label><label class="form-full">Notas internas<textarea name="notas" rows="3" maxlength="1000" placeholder="Pendientes, riesgos o información operativa">${esc(project.notas)}</textarea></label></div><div class="form-actions"><button type="button" class="btn-secondary" data-action="close-form">Cancelar</button><button type="submit" class="btn-primary">${editing?"Guardar cambios":"Crear proyecto"}</button></div></form>`;
}

function tableHTML(items){if(!items.length)return `<div class="empty-state"><strong>No hay proyectos registrados</strong><p class="muted">Crea el primer proyecto para comenzar el seguimiento operativo.</p><button class="btn-primary" data-action="new-project">+ Nuevo proyecto</button></div>`;return `<div class="client-table-wrap"><table class="client-table"><thead><tr><th>Proyecto</th><th>Cliente</th><th>Presupuesto</th><th>Estado</th><th>Responsable</th><th>Inicio</th><th>Cierre estimado</th><th></th></tr></thead><tbody>${items.map(p=>`<tr><td><strong>${esc(p.nombre||"Sin nombre")}</strong><small>${esc(p.descripcion||"")}</small></td><td>${esc(p.clienteNombre||"—")}</td><td>${p.presupuestoNumero?`<strong>${esc(p.presupuestoNumero)}</strong><small>$${Number(p.presupuestoTotalUSD||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}</small>`:"—"}</td><td><span class="status-pill status-${String(p.estado||"PLANIFICACION").toLowerCase()}">${statusLabel(p.estado||"PLANIFICACION")}</span></td><td>${esc(p.responsable||"—")}</td><td>${esc(dateText(p.fechaInicio))}</td><td>${esc(dateText(p.fechaFin))}</td><td class="table-actions"><button class="btn-table" data-action="edit" data-id="${esc(p.id)}">Editar</button></td></tr>`).join("")}</tbody></table></div>`;}

export async function renderProyectos(container){
 container.innerHTML=`<article class="card loading-card"><p class="muted">Cargando proyectos...</p></article>`;
 try{
  let [projects,clients,quotes]=await Promise.all([read("proyectos"),read("clientes"),read("presupuestos")]);
  const render=()=>{const term=(container.querySelector("#projectSearch")?.value||"").toLowerCase().trim();const list=projects.filter(p=>[p.nombre,p.clienteNombre,p.responsable,p.estado,p.presupuestoNumero].some(v=>String(v||"").toLowerCase().includes(term)));container.innerHTML=`<section class="project-module"><div class="module-toolbar"><div><span class="eyebrow">OPERACIONES</span><h2>Proyectos</h2><p class="muted">Seguimiento del trabajo desde la aprobación hasta la entrega.</p></div><div class="toolbar-actions"><input id="projectSearch" class="search-input" type="search" value="${esc(term)}" placeholder="Buscar proyecto, cliente o presupuesto..."><button class="btn-primary" data-action="new-project">+ Nuevo proyecto</button></div></div><div class="grid kpis"><article class="card stat-card"><h3>Total</h3><div class="metric">${projects.length}</div><p class="muted">Proyectos registrados</p></article><article class="card stat-card"><h3>En progreso</h3><div class="metric">${projects.filter(p=>p.estado==="EN_PROGRESO").length}</div><p class="muted">Trabajo activo</p></article><article class="card stat-card"><h3>Planificación</h3><div class="metric">${projects.filter(p=>p.estado==="PLANIFICACION").length}</div><p class="muted">Pendientes de ejecución</p></article><article class="card stat-card"><h3>Completados</h3><div class="metric">${projects.filter(p=>p.estado==="COMPLETADO").length}</div><p class="muted">Entregados</p></article></div><div class="card client-list-card"><div class="list-summary"><span>${list.length} proyecto${list.length===1?"":"s"}</span><span class="muted">Los proyectos conservan su historial operativo y comercial.</span></div><div id="projectTable">${tableHTML(list)}</div></div><div id="projectFormHost" class="client-form-host hidden"></div></section>`;
   container.querySelector("#projectSearch").addEventListener("input",render);
   container.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.action==="new-project")openForm();if(b.dataset.action==="edit")openForm(projects.find(p=>p.id===b.dataset.id));}));
  };
  const openForm=project=>{const host=container.querySelector("#projectFormHost");host.innerHTML=`<div class="client-form-card">${formHTML(clients,quotes,project||{})}</div>`;host.classList.remove("hidden");host.scrollIntoView({behavior:"smooth",block:"start"});host.querySelectorAll('[data-action="close-form"]').forEach(b=>b.addEventListener("click",()=>{host.classList.add("hidden");host.innerHTML="";}));
   const clientSelect=host.querySelector('[name="clienteId"]');const quoteSelect=host.querySelector('[name="presupuestoId"]');
   quoteSelect.addEventListener("change",()=>{const q=quotes.find(x=>x.id===quoteSelect.value);if(q&&q.clienteId){clientSelect.value=q.clienteId;}});
   host.querySelector("#projectForm").addEventListener("submit",async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const quote=quotes.find(q=>q.id===d.presupuestoId);const client=clients.find(c=>c.id===(quote?.clienteId||d.clienteId));const payload={nombre:String(d.nombre||"").trim(),clienteId:client?.id||"",clienteNombre:client?.nombre||"",clienteRif:client?.rif||"",presupuestoId:quote?.id||"",presupuestoNumero:quote?.numero||"",presupuestoTotalUSD:Number(quote?.totalUSD)||0,estado:statuses.includes(d.estado)?d.estado:"PLANIFICACION",responsable:String(d.responsable||"").trim(),fechaInicio:d.fechaInicio||"",fechaFin:d.fechaFin||"",descripcion:String(d.descripcion||"").trim(),notas:String(d.notas||"").trim(),updatedAt:serverTimestamp(),updatedBy:user()?.uid||null};if(!payload.nombre)return alert("El nombre del proyecto es obligatorio.");const id=e.currentTarget.dataset.id;try{if(id)await updateDoc(doc(db,"proyectos",id),payload);else await addDoc(collection(db,"proyectos"),{...payload,createdAt:serverTimestamp(),createdBy:user()?.uid||null});await renderProyectos(container);}catch(error){console.error(error);alert("No se pudo guardar el proyecto. Revisa Firestore.");}});
  };
  render();
 }catch(error){console.error(error);container.innerHTML=`<article class="card"><h3>No se pudo cargar Proyectos</h3><p class="muted">Revisa la conexión con Firestore y las reglas publicadas.</p></article>`;}
}
